"""Initial migration.

Revision ID: 09dcde64e36b
Revises: 
Create Date: 2024-09-29 19:43:54.918250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09dcde64e36b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college',
    sa.Column('college_id', sa.String(length=6), nullable=False),
    sa.Column('college_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('college_id')
    )
    op.create_table('conference',
    sa.Column('conference_id', sa.String(length=15), nullable=False),
    sa.Column('conference_title', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=30), nullable=True),
    sa.Column('conference_date', sa.Date(), nullable=True),
    sa.Column('date_added', sa.TIMESTAMP(), nullable=True),
    sa.Column('date_modified', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('conference_id')
    )
    op.create_table('publisher',
    sa.Column('publisher_id', sa.String(length=16), nullable=False),
    sa.Column('publisher_name', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('publisher_id')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.String(length=2), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('sdg',
    sa.Column('sdg_id', sa.String(length=6), nullable=False),
    sa.Column('sdg_desc', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('sdg_id')
    )
    op.create_table('account',
    sa.Column('user_id', sa.String(length=15), nullable=False),
    sa.Column('live_account', sa.String(length=80), nullable=True),
    sa.Column('user_pw', sa.String(length=64), nullable=True),
    sa.Column('acc_status', sa.String(length=20), server_default=sa.text("'ACTIVATED'"), nullable=True),
    sa.Column('role_id', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('program',
    sa.Column('program_id', sa.String(length=5), nullable=False),
    sa.Column('college_id', sa.String(length=6), nullable=True),
    sa.Column('program_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.college_id'], ),
    sa.PrimaryKeyConstraint('program_id')
    )
    op.create_table('audit_trail',
    sa.Column('audit_id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=15), nullable=True),
    sa.Column('table_name', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.String(length=16), nullable=True),
    sa.Column('operation', sa.String(length=50), nullable=True),
    sa.Column('change_datetime', sa.TIMESTAMP(), nullable=True),
    sa.Column('action_desc', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['account.user_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('research_outputs',
    sa.Column('research_id', sa.String(length=15), nullable=False),
    sa.Column('college_id', sa.String(length=6), nullable=True),
    sa.Column('program_id', sa.String(length=5), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('abstract', sa.String(length=1000), nullable=True),
    sa.Column('sdg_id', sa.String(length=6), nullable=True),
    sa.Column('keywords', sa.String(length=50), nullable=True),
    sa.Column('pdf', sa.String(length=100), nullable=True),
    sa.Column('date_submitted', sa.TIMESTAMP(), nullable=True),
    sa.Column('date_modified', sa.TIMESTAMP(), nullable=True),
    sa.Column('user_id', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.college_id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.program_id'], ),
    sa.ForeignKeyConstraint(['sdg_id'], ['sdg.sdg_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['account.user_id'], ),
    sa.PrimaryKeyConstraint('research_id')
    )
    op.create_table('researchers',
    sa.Column('researcher_id', sa.String(length=15), nullable=False),
    sa.Column('college_id', sa.String(length=6), nullable=True),
    sa.Column('program_id', sa.String(length=5), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('middle_name', sa.String(length=2), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('suffix', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.college_id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.program_id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['account.user_id'], ),
    sa.PrimaryKeyConstraint('researcher_id')
    )
    op.create_table('publications',
    sa.Column('publication_id', sa.String(length=16), nullable=False),
    sa.Column('research_id', sa.String(length=15), nullable=True),
    sa.Column('publication_format', sa.String(length=20), nullable=True),
    sa.Column('conference_id', sa.String(length=15), nullable=True),
    sa.Column('publisher_id', sa.String(length=16), nullable=True),
    sa.Column('publication_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('date_submitted', sa.TIMESTAMP(), nullable=True),
    sa.Column('date_modified', sa.TIMESTAMP(), nullable=True),
    sa.Column('user_id', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['conference_id'], ['conference.conference_id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.publisher_id'], ),
    sa.ForeignKeyConstraint(['research_id'], ['research_outputs.research_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['account.user_id'], ),
    sa.PrimaryKeyConstraint('publication_id')
    )
    op.create_table('research_output_authors',
    sa.Column('research_id', sa.String(length=15), nullable=False),
    sa.Column('author_id', sa.String(length=15), nullable=False),
    sa.Column('author_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['account.user_id'], ),
    sa.ForeignKeyConstraint(['research_id'], ['research_outputs.research_id'], ),
    sa.PrimaryKeyConstraint('research_id', 'author_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_output_authors')
    op.drop_table('publications')
    op.drop_table('researchers')
    op.drop_table('research_outputs')
    op.drop_table('audit_trail')
    op.drop_table('program')
    op.drop_table('account')
    op.drop_table('sdg')
    op.drop_table('roles')
    op.drop_table('publisher')
    op.drop_table('conference')
    op.drop_table('college')
    # ### end Alembic commands ###
